version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: kairix-neo4j
    ports:
      - "8290:8290"  # HTTP
      - "8289:8289"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/password

      # Enable plugins including GenAI for vector operations
      - NEO4J_PLUGINS=["apoc", "genai"]

      # APOC settings
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

      # Memory configuration for better performance with embeddings
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=2G

      # Enable procedures unrestricted for vector operations
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,genai.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,genai.*
